******************Start training**************************************
--------------------------------------------------------
Dataset size: training 7491, validation 830, testing 1670
--------------------------------------------------------
Namespace(TTA=False, batch_size=128, bias_whole_image=0.4, classify_only_ordered_images_or_not=True, domains_list=['photo', 'sketch', 'cartoon', 'art_painting'], entropy_loss_weight=0.1, epochs=30, folder_name='test', image_size=222, jitter=0.4, learning_rate=0.001, limit_source=None, limit_target=None, max_scale=1.0, min_scale=0.8, n_classes=7, nesterov=False, network='resnet18', ooo_weight=0, parameters_lists=[[0.8, 0.4, 0.8, 0.1]], random_horiz_flip=0.5, repeat_times=1, source=['sketch', 'cartoon', 'art_painting'], suffix='', target='photo', target_domain_list=['photo'], target_domain_unsupervised_task_loss_weight=0.8, tf_logger=True, tile_random_grayscale=0.1, train_all=True, unsupervised_task_weight=0.8, val_size=0.1)
--------------------------------------------------------
/home/giorgio/Files/pycharm_project/pytorch_interpreter/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:100: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
--------------------------------------------------------
current epoch:%d 0
New epoch - lr: 0.001
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/giorgio/Files/softwares/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/giorgio/Files/softwares/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/giorgio/Files/pycharm_project/pytorch_interpreter/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 25, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/giorgio/Files/softwares/anaconda3/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/giorgio/Files/pycharm_project/pytorch_interpreter/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    fd = df.detach()
  File "/home/giorgio/Files/softwares/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/giorgio/Files/softwares/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/giorgio/Files/softwares/anaconda3/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/home/giorgio/Files/softwares/anaconda3/lib/python3.7/multiprocessing/connection.py", line 619, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

Traceback (most recent call last):
  File "/home/giorgio/Files/pycharm_project/DG_rotation/DA_rotation_trainer.py", line 283, in <module>
    lazy_train(DA_rotation_training_argument, output_manager)
  File "/home/giorgio/Files/pycharm_project/DG_rotation/DA_rotation_trainer.py", line 237, in lazy_train
    trainer.do_training()
  File "/home/giorgio/Files/pycharm_project/DG_rotation/DA_rotation_trainer.py", line 190, in do_training
    self._do_epoch()
  File "/home/giorgio/Files/pycharm_project/DG_rotation/DA_rotation_trainer.py", line 57, in _do_epoch
    in enumerate(zip(self.source_domain_train_data_loader, itertools.cycle(self.target_domain_train_data_loader))):
  File "/home/giorgio/Files/pycharm_project/pytorch_interpreter/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "/home/giorgio/Files/pycharm_project/pytorch_interpreter/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 761, in _get_data
    success, data = self._try_get_data()
  File "/home/giorgio/Files/pycharm_project/pytorch_interpreter/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/giorgio/Files/softwares/anaconda3/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/home/giorgio/Files/softwares/anaconda3/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
